### ISSUE TITLE
updateExchangeState.getFills() is empty

### ISSUE THREAD

**Issue by ActTraderMobile** [CCob/bittrex4j#46] opened 2018-09-26 09:25 UTC
com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "FI" (class com.github.ccob.bittrex4j.dao.Fill), not marked as ignorable (15 known properties: "Rate", "Total", "OrderType", "Price", "Quantity", "TimeStamp", "Id", "FillType", "total", "orderType", "quantity", "timeStamp", "id", "fillType", "price"])
 at [Source: (org.apache.http.client.entity.DeflateInputStream); line: 1, column: 243] (through reference chain: com.github.ccob.bittrex4j.dao.Fill["FI"])

**Comment by CCob** [comment] 2018-09-26 09:31
Duplicate of #42

**Closed by CCob** 2018-09-26 09:31 UTC
Labels: duplicate
